---
- name: debian | Adding Elasticsearch Repo Key
  apt_key:
    url: "{{ kibana_debian_repo_info.key }}"
    state: "present"

- name: debian | Adding Kibana Repo
  apt_repository:
    repo: "{{ kibana_debian_repo_info.repo }}"
    state: "present"

- name: debian | Installing Kibana
  apt:
    name: "kibana={{ kibana_version }}"
    state: "present"
