---
# tasks file for ansible-elk-kibana
- include: remove_legacy_install.yml
  when: remove_legacy_kibana_install

- include: debian.yml
  tags:
    - kibana
    - upgrade_kibana
  when: ansible_os_family == "Debian"

- include: centos.yml
  tags:
    - kibana
    - upgrade_kibana
  when: ansible_os_family == "RedHat"

- include: config_kibana.yml
  tags:
    - kibana
    - upgrade_kibana
  when: config_kibana
